#!/usr/bin/env ruby
# frozen_string_literal: true

# for dev purposes
require 'bundler/setup' if ENV['URL_FINDER_GEM_DEV']

require 'url_finder'
require 'optparse'

options = {}
OptionParser.new do |parser|
  parser.banner = 'Usage: url_finder --help'
  parser.default_argv = ARGV

  parser.on('--file=/path/to/file', String, 'Input file') do |string|
    options[:file] = string
  end

  parser.on('--format=file_format', String, 'Input format (html, markdown, csv, string)') do |string|
    options[:format] = string
  end

  parser.on('-h', '--help', 'How to use') do
    puts parser
    exit
  end
end.parse!

file = options.fetch(:file) { raise(ArgumentError, '--file is required') }
file_format = options[:format]

UrlFinder.from_file(file, file_format).each do |url|
  puts url
end
